# This was generated by terraformer and I edited it to make it more generic. The name for all of my resources is acgpractice733.

resource "aws_iam_policy" "KinesisFirehoseServicePolicy-PUT-S3-acgpractice733" {
  name   = "KinesisFirehoseServicePolicy-PUT-S3-acgpractice733"
  path   = "/service-role/"
  policy = data.aws_iam_policy_document.KinesisFirehoseServicePolicy-PUT-S3-acgpractice733.json
}

data "aws_iam_policy_document" "KinesisFirehoseServicePolicy-PUT-S3-acgpractice733" {
  statement {
    actions = [
      "s3:*",
      "logs:*",
      "kinesis:*"
    ]
    effect    = "Allow"
    resources = ["*"]
  }
}
