# This was generated by terraformer and I edited it to make it more generic. The name for all of my resources is acgpractice733.

resource "aws_s3_bucket" "acgpractice733" {
  bucket              = "acgpractice733"
  force_destroy       = "false"
  object_lock_enabled = "false"
}
