# This was generated by terraformer and I edited it to make it more generic. The name for all of my resources is acgpractice733.

resource "aws_iam_role" "sagemaker-full-access-role" {
  assume_role_policy = <<POLICY
{
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "Service": "sagemaker.amazonaws.com"
      },
      "Action": "sts:AssumeRole"
    }
  ],
  "Version": "2012-10-17"
}
POLICY

  managed_policy_arns   = ["arn:aws:iam::aws:policy/AmazonSageMakerFullAccess"]
  max_session_duration  = "3600"
  name                  = "sagemaker-full-access-role"
  path                  = "/service-role/"
  force_detach_policies = true
}
