# This was generated by terraformer and I edited it to make it more generic. The name for all of my resources is acgpractice733.

resource "aws_kinesis_firehose_delivery_stream" "PUT-S3-acgpractice733" {
  name        = "PUT-S3-acgpractice733"
  destination = "extended_s3"

  extended_s3_configuration {
    bucket_arn         = "arn:aws:s3:::acgpractice733"
    buffering_interval = "10"
    buffering_size     = "5"

    processing_configuration {
      enabled = "true"

      processors {
        type = "AppendDelimiterToRecord"
      }
    }

    cloudwatch_logging_options {
      enabled         = "true"
      log_group_name  = "/aws/kinesisfirehose/PUT-S3-acgpractice733"
      log_stream_name = "DestinationDelivery"
    }

    compression_format = "UNCOMPRESSED"
    role_arn           = "arn:aws:iam::${data.aws_caller_identity.current.account_id}:role/service-role/KinesisFirehoseServiceRole-PUT-S3-acgpractice733"
    s3_backup_mode     = "Disabled"
  }

  server_side_encryption {
    enabled = "false"
  }
}
